---
name: Deploy to Fly

on:
    push:
        branches:
            - main

jobs:
    deploy-fly:

        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

        runs-on: ubuntu-latest
        if: github.repository_owner == 'marda-alliance'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  submodules: true

            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
                  cache: pip
                  cache-dependency-path: pyproject.toml

            - name: Install dependencies
              run: pip install .

            - name: Generate Python models
              run: invoke regenerate-models

            - name: Set up Fly
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Deploy to Fly
              run: flyctl deploy --remote-only -c ./.github/fly.toml
